**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*    Modeling services provided by   *
* Interface Technologies www.i-t.com *
**************************************
.MODEL Qmjl21194 npn
+IS=9.56205e-11 BF=62.3633 NF=0.858602 VAF=29.6613
+IKF=9.86004 ISE=7.00007e-12 NE=3.43749 BR=4.96358
+NR=0.925054 VAR=6.18692 IKR=4.87016 ISC=3.25e-13
+NC=4 RB=11.0204 IRB=0.1 RBM=0.1
+RE=0.000675706 RC=0.124974 XTB=0.150823 XTI=1.00001
+EG=1.11955 CJE=1.70807e-08 VJE=0.4 MJE=0.520397
+TF=1e-08 XTF=47.3046 VTF=1.88154 ITF=0.560261
+CJC=5e-10 VJC=0.95 MJC=0.238884 XCJC=0.800727
+FC=0.8 CJS=0 VJS=0.75 MJS=0.5
+TR=1e-07 PTF=0 KF=0 AF=1
* Model generated on Jan 25, 2004
* Model format: PSpice
