**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*    Modeling services provided by   *
* Interface Technologies www.i-t.com *
**************************************
.MODEL Qmjl21193 pnp
+IS=2.37302e-11 BF=92.8585 NF=0.85 VAF=1000
+IKF=7.81463 ISE=9.34142e-13 NE=1.83168 BR=1.39987
+NR=0.905395 VAR=421.163 IKR=1.8668 ISC=9.34142e-13
+NC=3.03125 RB=14.6266 IRB=0.1 RBM=0.149902
+RE=0.000682292 RC=0.146081 XTB=1.32633 XTI=1.05623
+EG=1.05 CJE=1.15773e-08 VJE=0.57352 MJE=0.417157
+TF=1e-08 XTF=1.946 VTF=17401.6 ITF=3.36265
+CJC=5e-10 VJC=0.95 MJC=0.23891 XCJC=0.999998
+FC=0.987529 CJS=0 VJS=0.75 MJS=0.5
+TR=1e-07 PTF=0 KF=0 AF=1
* Model generated on Jan 25, 2004
* Model format: PSpice
